using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameInput : MonoBehaviour
{
    // singelton


    private PlayerInputActions playerInputActions;
    private void Awake()
    {
        /*
         * using the new input system:
         * PlayerInputActions - the Input Actions Asset we created, also a c# code autogenerated 
         * playerInputActions - An instance of the PlayerInputActions Class
         * playerInputActions.Player - an action map we created for handling player input
        */ 
        playerInputActions = new PlayerInputActions();
        playerInputActions.Player.Enable();
    }

    public Vector2 GetTopDownMovementVectorNormalized()
    {
        // read the value as how we define in the action
        Vector2 inputVector = playerInputActions.Player.Move_TopDown.ReadValue<Vector2>();

        inputVector = inputVector.normalized;

        return inputVector;
    }
}
