using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameInput : MonoBehaviour
{
    // singelton

    // an EventHandler delegate in GameInput class so that other classes can grab access and listen to
    public event EventHandler OnInteractAction;
    public event EventHandler OnInteractAlternateAction;

    private PlayerInputActions playerInputActions;
    private void Awake()
    {
        /*
         * using the new input system:
         * PlayerInputActions - the Input Actions Asset we created, also a c# code autogenerated 
         * playerInputActions - An instance of the PlayerInputActions Class
         * playerInputActions.Player - an action map we created for handling player input
        */ 
        playerInputActions = new PlayerInputActions();
        playerInputActions.Player.Enable();

        // subscribe a listener to playerInputActions' Interact performed event, so we know when the interact input action is performed
        playerInputActions.Player.Interact.performed += Interact_performed;
        playerInputActions.Player.InteractAlternate.performed += InteractAlternate_performed;
    }

    private void InteractAlternate_performed(UnityEngine.InputSystem.InputAction.CallbackContext obj)
    {
        OnInteractAlternateAction?.Invoke(this, EventArgs.Empty);
    }

    private void Interact_performed(UnityEngine.InputSystem.InputAction.CallbackContext obj)
    {
        OnInteractAction?.Invoke(this, EventArgs.Empty);
    }

    public Vector2 GetTopDownMovementVectorNormalized()
    {
        // read the value as how we define in the action
        Vector2 inputVector = playerInputActions.Player.Move.ReadValue<Vector2>();

        inputVector = inputVector.normalized;

        return inputVector;
    }
}
